import livro from '../../imagens/livro.png' 

export const livros = [
        { nome: 'Liderança em Design', id: 1, src: livro },
        { nome: 'Liderança em UX', id: 2, src: livro },
        { nome: 'Javascript assertivo', id: 3, src: livro },
        { nome: 'Cangaceiro em Javascript', id: 4, src: livro },
        { nome: 'Aventureiros do Java', id: 5, src: livro },
        { nome: 'React na Prática', id: 6, src: livro },
        { nome: 'Node.js Avançado', id: 7, src: livro },
        { nome: 'Python para Iniciantes', id: 8, src: livro },
        { nome: 'Desenvolvimento Ágil', id: 9, src: livro },
        { nome: 'UI/UX Design Essentials', id: 10, src: livro },
        { nome: 'Machine Learning Fundamentals', id: 11, src: livro },
        { nome: 'Data Science for Beginners', id: 12, src: livro },
        { nome: 'Web Development with Django', id: 13, src: livro },
        { nome: 'Building Scalable Apps', id: 14, src: livro },
        { nome: 'Frontend Frameworks Comparison', id: 15, src: livro },
        { nome: 'Introdução à Inteligência Artificial', id: 16, src: livro },
        { nome: 'Blockchain Explained', id: 17, src: livro },
        { nome: 'Design Patterns in Software Engineering', id: 18, src: livro },
        { nome: 'Sistemas Distribuídos', id: 19, src: livro },
        { nome: 'UX Research Techniques', id: 20, src: livro },
        { nome: 'Mobile App Development', id: 21, src: livro },
        { nome: 'Full Stack Web Development', id: 22, src: livro },
        { nome: 'DevOps Essentials', id: 23, src: livro },
        { nome: 'Product Management', id: 24, src: livro },
        { nome: 'User-Centered Design', id: 25, src: livro },
        { nome: 'Swift Programming for iOS', id: 26, src: livro },
        { nome: 'Android App Development', id: 27, src: livro },
        { nome: 'Java Programming', id: 28, src: livro },
        { nome: 'HTML5 and CSS3', id: 29, src: livro },
        { nome: 'Database Design and SQL', id: 30, src: livro },
        { nome: 'Cloud Computing', id: 31, src: livro },
        { nome: 'Network Security', id: 32, src: livro },
        { nome: 'Artificial Intelligence in Business', id: 33, src: livro },
        { nome: 'Responsive Web Design', id: 34, src: livro },
        { nome: 'Vue.js Essentials', id: 35, src: livro },
        { nome: 'Angular Development', id: 36, src: livro },
        { nome: 'Java Spring Framework', id: 37, src: livro },
        { nome: 'C# Programming', id: 38, src: livro },
        { nome: 'Linux System Administration', id: 39, src: livro },
        { nome: 'Microservices Architecture', id: 40, src: livro },
        { nome: 'Agile Project Management', id: 41, src: livro },
        { nome: 'Python Data Analysis', id: 42, src: livro },
        { nome: 'Raspberry Pi Projects', id: 43, src: livro },
        { nome: 'Cybersecurity Fundamentals', id: 44, src: livro },
        { nome: 'Kotlin Programming', id: 45, src: livro },
        { nome: 'IoT Essentials', id: 46, src: livro },
        { nome: 'Game Development with Unity', id: 47, src: livro },
        { nome: 'Digital Marketing Strategies', id: 48, src: livro },
        { nome: 'TensorFlow Essentials', id: 49, src: livro },
        { nome: 'Augmented Reality Development', id: 50, src: livro },
        { nome: 'iOS App Development', id: 51, src: livro },
        { nome: 'Android Kotlin Development', id: 52, src: livro },
        { nome: 'SwiftUI Essentials', id: 53, src: livro },
        { nome: 'Data Visualization with D3.js', id: 54, src: livro },
        { nome: 'Scrum Master Certification', id: 55, src: livro },
        { nome: 'Vue.js Advanced Techniques', id: 56, src: livro },
        { nome: 'Node.js Security', id: 57, src: livro },
        { nome: 'JavaFX Programming', id: 58, src: livro },
        { nome: 'Cloud Native Architecture', id: 59, src: livro },
        { nome: 'UI/UX Design Trends', id: 60, src: livro },
        { nome: 'Artificial Intelligence in Healthcare', id: 61, src: livro },
        { nome: 'Blockchain Applications', id: 62, src: livro },
        { nome: 'React Native Development', id: 63, src: livro },
        { nome: 'Micro Frontends', id: 64, src: livro },
        { nome: 'GraphQL Essentials', id: 65, src: livro },
        { nome: 'Big Data Analytics', id: 66, src: livro },
        { nome: 'Serverless Computing', id: 67, src: livro },
        { nome: 'Ethical Hacking', id: 68, src: livro },
        { nome: 'User Interface Design Principles', id: 69, src: livro },
        { nome: 'JavaScript Design Patterns', id: 70, src: livro },
        { nome: 'Docker Essentials', id: 71, src: livro },
        { nome: 'Vue.js and Nuxt.js Development', id: 72, src: livro },
        { nome: 'Java Microservices', id: 73, src: livro },
        { nome: 'CSS Grid Layout', id: 74, src: livro },
        { nome: 'Artificial Intelligence Ethics', id: 75, src: livro },
        { nome: 'Swift Programming for macOS', id: 76, src: livro },
        { nome: 'Android Studio Development', id: 77, src: livro },
        { nome: 'Responsive Email Design', id: 78, src: livro },
        { nome: 'Data Warehousing', id: 79, src: livro },
        { nome: 'UI/UX Prototyping', id: 80, src: livro },
        { nome: 'JavaScript Design Patterns', id: 70, src: livro },
        { nome: 'Docker Essentials', id: 71, src: livro },
        { nome: 'Vue.js and Nuxt.js Development', id: 72, src: livro },
        { nome: 'Java Microservices', id: 73, src: livro },
        { nome: 'CSS Grid Layout', id: 74, src: livro },
        { nome: 'Artificial Intelligence Ethics', id: 75, src: livro },
        { nome: 'Swift Programming for macOS', id: 76, src: livro },
        { nome: 'Android Studio Development', id: 77, src: livro },
        { nome: 'Responsive Email Design', id: 78, src: livro },
        { nome: 'Data Warehousing', id: 79, src: livro },
        { nome: 'UI/UX Prototyping', id: 80, src: livro },
        { nome: 'JavaScript Frameworks Comparison', id: 81, src: livro },
        { nome: 'Python Machine Learning', id: 82, src: livro },
        { nome: 'Software Testing Best Practices', id: 83, src: livro },
        { nome: 'WebAssembly Essentials', id: 84, src: livro },
        { nome: 'Mobile App Usability', id: 85, src: livro },
        { nome: 'Cryptography Basics', id: 86, src: livro },
        { nome: 'JavaFX UI Design', id: 87, src: livro },
        { nome: 'Cloud Security', id: 88, src: livro },
        { nome: 'User-Centric Mobile Design', id: 89, src: livro },
        { nome: 'JavaScript Animation Techniques', id: 90, src: livro },
        { nome: 'Server-Side Rendering with React', id: 91, src: livro },
        { nome: 'React Hooks', id: 92, src: livro },
        { nome: 'Progressive Web Apps', id: 93, src: livro },
        { nome: 'Java Concurrency', id: 94, src: livro },
        { nome: 'UI/UX for E-commerce', id: 95, src: livro },
        { nome: 'Cloud-Native Data Management', id: 96, src: livro },
        { nome: 'Android Material Design', id: 97, src: livro },
        { nome: 'Python Web Scraping', id: 98, src: livro },
        { nome: 'Micro Frontends Architecture', id: 99, src: livro },
        { nome: 'Cybersecurity for Developers', id: 100, src: livro },
        { nome: 'Data Governance', id: 101, src: livro },
        { nome: 'Design Thinking in Software Development', id: 102, src: livro },
        { nome: 'Android Jetpack Components', id: 103, src: livro },
        { nome: 'Vue.js State Management', id: 104, src: livro },
        { nome: 'Java Design Patterns', id: 105, src: livro },
];